/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace Ruyi.SDK.Constants
{
  public static class ConstantsSDKDataTypesConstants
  {
    /// <summary>
    /// @low_latency_socket_port_desc
    /// </summary>
    public const int low_latency_socket_port = 11290;
    /// <summary>
    /// @high_latency_socket_port_desc
    /// </summary>
    public const int high_latency_socket_port = 11390;
    /// <summary>
    /// @layer0_broker_address_desc
    /// </summary>
    public const string layer0_broker_address = "tcp://{addr}:5555";
    /// <summary>
    /// @layer0_publisher_in_uri_desc
    /// </summary>
    public const string layer0_publisher_in_uri = "tcp://{addr}:5567";
    /// <summary>
    /// @layer0_publisher_out_uri_desc
    /// </summary>
    public const string layer0_publisher_out_uri = "tcp://{addr}:5568";
    /// <summary>
    /// @setting_config_folder_desc
    /// </summary>
    public const string setting_config_folder = "resources/configs/";
    /// <summary>
    /// @setting_system_config_desc
    /// </summary>
    public const string setting_system_config = "resources/configs/systemsetting";
    /// <summary>
    /// @setting_system_user_config_desc
    /// </summary>
    public const string setting_system_user_config = "resources/configs/usersetting";
    /// <summary>
    /// @system_setting_version_desc
    /// </summary>
    public const string system_setting_version = "1.0.0.1";
    /// <summary>
    /// @layer0_debugger_channel_desc
    /// </summary>
    public const string layer0_debugger_channel = "layer0_debugger_channel";
    /// <summary>
    /// @trc_test_channel_desc
    /// </summary>
    public const string trc_test_channel = "trc_test_channel";
    /// <summary>
    /// @broker_playback_message_desc
    /// </summary>
    public const string broker_playback_message = "mmi.developer.playback";
  }
}
