/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace Ruyi.SDK.CommonType
{

  public partial class InputActionInfo : TBase
  {
    private string _ActionName;
    private ActionTriggerInfo _TriggerInfo;

    public string ActionName
    {
      get
      {
        return _ActionName;
      }
      set
      {
        __isset.ActionName = true;
        this._ActionName = value;
      }
    }

    public ActionTriggerInfo TriggerInfo
    {
      get
      {
        return _TriggerInfo;
      }
      set
      {
        __isset.TriggerInfo = true;
        this._TriggerInfo = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool ActionName;
      public bool TriggerInfo;
    }

    public InputActionInfo()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                ActionName = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                TriggerInfo = new ActionTriggerInfo();
                await TriggerInfo.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("InputActionInfo");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (ActionName != null && __isset.ActionName)
        {
          field.Name = "ActionName";
          field.Type = TType.String;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(ActionName, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (TriggerInfo != null && __isset.TriggerInfo)
        {
          field.Name = "TriggerInfo";
          field.Type = TType.Struct;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await TriggerInfo.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("InputActionInfo(");
      bool __first = true;
      if (ActionName != null && __isset.ActionName)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("ActionName: ");
        sb.Append(ActionName);
      }
      if (TriggerInfo != null && __isset.TriggerInfo)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("TriggerInfo: ");
        sb.Append(TriggerInfo== null ? "<null>" : TriggerInfo.ToString());
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
