/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Ruyi.SDK.Overlay
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class OverlayState : TBase
  {
    private bool _isVisible;
    private string _arguments;

    public bool IsVisible
    {
      get
      {
        return _isVisible;
      }
      set
      {
        __isset.isVisible = true;
        this._isVisible = value;
      }
    }

    public string Arguments
    {
      get
      {
        return _arguments;
      }
      set
      {
        __isset.arguments = true;
        this._arguments = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool isVisible;
      public bool arguments;
    }

    public OverlayState() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                IsVisible = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Arguments = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("OverlayState");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.isVisible) {
          field.Name = "isVisible";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(IsVisible);
          oprot.WriteFieldEnd();
        }
        if (Arguments != null && __isset.arguments) {
          field.Name = "arguments";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Arguments);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("OverlayState(");
      bool __first = true;
      if (__isset.isVisible) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IsVisible: ");
        __sb.Append(IsVisible);
      }
      if (Arguments != null && __isset.arguments) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Arguments: ");
        __sb.Append(Arguments);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
