/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;


namespace Ruyi.SDK.GlobalInputDefine
{
  public static class GlobalInputDefineSDKDataTypesConstants
  {
    /// <summary>
    /// From 0 to 255
    /// </summary>
    public const sbyte AnalogChangeSensitivity = 1;
    /// <summary>
    /// From 0 to 255
    /// </summary>
    public const sbyte AnalogTriggerActionValue = 30;
    /// <summary>
    /// In miniseconds.
    /// </summary>
    public const int RuyiInputCombineTime = 230;
    public const int RuyiGamepadJoyDefaultValue = 128;
  }
}
