/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ruyi.SDK.GlobalInputDefine
{
  public enum RuyiInputDeviceType
  {
    XB360 = 0,
    Mouse = 1,
    Keyboard = 2,
    Joystick = 3,
    Gamepad = 4,
    Driving = 5,
    Flight = 6,
    FirstPerson = 7,
    ControlDevice = 8,
    ScreenPointer = 9,
    Remote = 10,
    Supplemental = 11,
    RuyiController = 100,
  }
}
