/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ruyi.SDK.GlobalInputDefine
{
  public enum RuyiActionActivateEvent
  {
    eKeyDown = 1,
    eKeyUp = 2,
    eKeyDownAndUp = 3,
  }
}
