/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Ruyi.SDK.CommonType
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ActionTriggerInfo : TBase
  {
    private InputCagetory _InputCagetory;
    private List<InputIdentifier> _TriggerConditions;
    private bool _AutoTrigger;
    private int _TriggerInterval;

    /// <summary>
    /// 
    /// <seealso cref="InputCagetory"/>
    /// </summary>
    public InputCagetory InputCagetory
    {
      get
      {
        return _InputCagetory;
      }
      set
      {
        __isset.InputCagetory = true;
        this._InputCagetory = value;
      }
    }

    public List<InputIdentifier> TriggerConditions
    {
      get
      {
        return _TriggerConditions;
      }
      set
      {
        __isset.TriggerConditions = true;
        this._TriggerConditions = value;
      }
    }

    public bool AutoTrigger
    {
      get
      {
        return _AutoTrigger;
      }
      set
      {
        __isset.AutoTrigger = true;
        this._AutoTrigger = value;
      }
    }

    public int TriggerInterval
    {
      get
      {
        return _TriggerInterval;
      }
      set
      {
        __isset.TriggerInterval = true;
        this._TriggerInterval = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool InputCagetory;
      public bool TriggerConditions;
      public bool AutoTrigger;
      public bool TriggerInterval;
    }

    public ActionTriggerInfo() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                InputCagetory = (InputCagetory)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  TriggerConditions = new List<InputIdentifier>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    InputIdentifier _elem2;
                    _elem2 = new InputIdentifier();
                    _elem2.Read(iprot);
                    TriggerConditions.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                AutoTrigger = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                TriggerInterval = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ActionTriggerInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.InputCagetory) {
          field.Name = "InputCagetory";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)InputCagetory);
          oprot.WriteFieldEnd();
        }
        if (TriggerConditions != null && __isset.TriggerConditions) {
          field.Name = "TriggerConditions";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, TriggerConditions.Count));
            foreach (InputIdentifier _iter3 in TriggerConditions)
            {
              _iter3.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.AutoTrigger) {
          field.Name = "AutoTrigger";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(AutoTrigger);
          oprot.WriteFieldEnd();
        }
        if (__isset.TriggerInterval) {
          field.Name = "TriggerInterval";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(TriggerInterval);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ActionTriggerInfo(");
      bool __first = true;
      if (__isset.InputCagetory) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InputCagetory: ");
        __sb.Append(InputCagetory);
      }
      if (TriggerConditions != null && __isset.TriggerConditions) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TriggerConditions: ");
        __sb.Append(TriggerConditions);
      }
      if (__isset.AutoTrigger) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AutoTrigger: ");
        __sb.Append(AutoTrigger);
      }
      if (__isset.TriggerInterval) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TriggerInterval: ");
        __sb.Append(TriggerInterval);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
