/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ruyi.SDK.CommonType
{
  public enum LoginState
  {
    /// <summary>
    /// Logout state
    /// </summary>
    Logout = 0,
    /// <summary>
    /// Login state
    /// </summary>
    Login = 1,
  }
}
