/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ruyi.SDK.CommonType
{
  public enum NotificationType
  {
    Title = 0,
    TitleAnd2Icons = 1,
    TitleAndDescription = 2,
    TitleDetail = 3,
    Voice = 4,
  }
}
