/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ruyi.SDK.CommonType
{
  /// <summary>
  /// @OverlayCursor_desc
  /// </summary>
  public enum OverlayCursor
  {
    Auto = 0,
    Hardware = 1,
    Software = 2,
  }
}
