/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Ruyi.SDK.CommonType
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class range : TBase
  {
    private double _minimum;
    private double _maximum;

    public double Minimum
    {
      get
      {
        return _minimum;
      }
      set
      {
        __isset.minimum = true;
        this._minimum = value;
      }
    }

    public double Maximum
    {
      get
      {
        return _maximum;
      }
      set
      {
        __isset.maximum = true;
        this._maximum = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool minimum;
      public bool maximum;
    }

    public range() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Double) {
                Minimum = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Double) {
                Maximum = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("range");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.minimum) {
          field.Name = "minimum";
          field.Type = TType.Double;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(Minimum);
          oprot.WriteFieldEnd();
        }
        if (__isset.maximum) {
          field.Name = "maximum";
          field.Type = TType.Double;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(Maximum);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("range(");
      bool __first = true;
      if (__isset.minimum) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Minimum: ");
        __sb.Append(Minimum);
      }
      if (__isset.maximum) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Maximum: ");
        __sb.Append(Maximum);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
