/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace Ruyi.SDK.SettingSystem.Api
{

  public partial class NodeList : TBase
  {
    private List<SettingCategory> _SettingCategories;
    private List<SettingItem> _SettingItems;

    public List<SettingCategory> SettingCategories
    {
      get
      {
        return _SettingCategories;
      }
      set
      {
        __isset.SettingCategories = true;
        this._SettingCategories = value;
      }
    }

    public List<SettingItem> SettingItems
    {
      get
      {
        return _SettingItems;
      }
      set
      {
        __isset.SettingItems = true;
        this._SettingItems = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool SettingCategories;
      public bool SettingItems;
    }

    public NodeList()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  SettingCategories = new List<SettingCategory>();
                  TList _list18 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i19 = 0; _i19 < _list18.Count; ++_i19)
                  {
                    SettingCategory _elem20;
                    _elem20 = new SettingCategory();
                    await _elem20.ReadAsync(iprot, cancellationToken);
                    SettingCategories.Add(_elem20);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.List)
              {
                {
                  SettingItems = new List<SettingItem>();
                  TList _list21 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i22 = 0; _i22 < _list21.Count; ++_i22)
                  {
                    SettingItem _elem23;
                    _elem23 = new SettingItem();
                    await _elem23.ReadAsync(iprot, cancellationToken);
                    SettingItems.Add(_elem23);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("NodeList");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (SettingCategories != null && __isset.SettingCategories)
        {
          field.Name = "SettingCategories";
          field.Type = TType.List;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.Struct, SettingCategories.Count), cancellationToken);
            foreach (SettingCategory _iter24 in SettingCategories)
            {
              await _iter24.WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (SettingItems != null && __isset.SettingItems)
        {
          field.Name = "SettingItems";
          field.Type = TType.List;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.Struct, SettingItems.Count), cancellationToken);
            foreach (SettingItem _iter25 in SettingItems)
            {
              await _iter25.WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("NodeList(");
      bool __first = true;
      if (SettingCategories != null && __isset.SettingCategories)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("SettingCategories: ");
        sb.Append(SettingCategories);
      }
      if (SettingItems != null && __isset.SettingItems)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("SettingItems: ");
        sb.Append(SettingItems);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
